Feature/#38 use script
AKABANEDAI-FES/2024-programing-experience pull request #41
Opened 2024-10-09 15:31 UTC by Sho0226

## ⭐️ 概要

- 変更点 1
- 変更点 2
- 変更点 3
# 📷 動作デモ
https://github.com/user-attachments/assets/e04c2b7b-df90-4fbe-bf1a-6fb7311601b7

## 😎 目的

## 📷 動作デモ

## 💬 関連する Issue

## 🖋️ 補足事項

2024-10-09 20:03 UTC, yossuli requested changes

2024-10-09 20:03 UTC, yossuli commented on client/hooks/useScripts.tsx
> +  }, []);
`scripts`関係ないのでここで定義するのは不適かもです
定義するなら`utils/`ですかね...？
そもそもこの関数ってつかわれてるんでしょうか...？

2024-10-10 08:13 UTC, Sho0226 commented on client/hooks/useScripts.tsx
> +  }, []);
> `scripts`関係ないのでここで定義するのは不適かもです 定義するなら`utils/`ですかね...？ そもそもこの関数ってつかわれてるんでしょうか...？

@yossuli Playground内の<review >の動作以外は問題ないと思うから確認お願いします。

2024-10-10 09:27 UTC, yossuli requested changes

2024-10-10 09:27 UTC, yossuli commented on client/features/playground/Playground.tsx
> +  const scripts: Block[][] = [];
不要
仮に書くとしても
```tsx
const {scripts, setScripts} = useScript()
```
みたいな感じじゃないですかね

2024-10-10 09:27 UTC, yossuli commented on client/features/playground/Playground.tsx
> +      <Preview scripts={scripts} key={JSON.stringify(scripts)} />
propsでscriptsは渡さないのでいらないです
`'./preview/Preview'`側も変更お願いします

2024-10-10 09:27 UTC, yossuli commented on client/utils/dragUtils.ts
> +};
（一般的にどうなのかは別にして）僕としてはほかに似たような関数をutilsに入れたくなった時に扱いやすいファイル名なので好みです

2024-10-10 15:22 UTC, yossuli approved these changes
LGTM

2024-10-10 15:22 UTC, merged