markdownと１個ずつ/すべての表示ボタン
AKABANEDAI-FES/2024-programing-experience pull request #63
Opened 2024-10-21 13:40 UTC by s1f102201391

## ⭐️ 概要

-npm install react-markdown  で外部ライブラリのインストール
-１個ずつのボタンと全ての表示ボタンの実装

## 😎 目的

## 📷 スクリーンショット

## 💬 関連する Issue

## 🖋️ 補足事項

2024-10-24 07:36 UTC, yossuli requested changes

2024-10-24 07:36 UTC, yossuli commented on client/features/quest/component/start.tsx
消しましょう...
`git stash`するといいと思います

2024-10-24 07:36 UTC, yossuli commented on client/features/quest/component/Button.tsx
> +);
これだけ見ても何もわからないのでスクショの添付お願いします

2024-10-26 14:23 UTC, s1f102201391 commented
![スクリーンショット 2024-10-26 230301](https://github.com/user-attachments/assets/8a37d1f5-f909-4524-8f11-889ac60b4fa4)
今は見た目こんな感じです

2024-10-31 06:49 UTC, yossuli requested changes

2024-10-31 06:49 UTC, yossuli commented on package.json
> +    "tailwind-merge": "^2.5.4"
`uninstall`してほしいです

2024-11-01 04:39 UTC, merged